// Generated by Flow Studio from the examples of frontend/utils/pyrcode-input. Do not edit — add examples to the node instead.
// checksum: 2f5896b93a
import { describe, it, expect } from 'vitest';
import { pyrcodeInput } from './pyrcode-input';

describe("frontend/utils/pyrcode-input", () => {
  it("surrounding spaces from a scanner are dropped", async () => {
    expect(await pyrcodeInput({"typed":"  PYR-LT123 "} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"PYR-LT123","complete":true});
  });

  it("lower case is read as the upper case the backend generates", async () => {
    expect(await pyrcodeInput({"typed":"pyr-kb456"} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"PYR-KB456","complete":true});
  });

  it("a numbered copy of an item is a whole code", async () => {
    expect(await pyrcodeInput({"typed":"PYR-LT12-2"} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"PYR-LT12-2","complete":true});
  });

  it("the prefix alone is not a code yet", async () => {
    expect(await pyrcodeInput({"typed":"PYR-"} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"PYR-","complete":false});
  });

  it("a category without a number is not a code yet", async () => {
    expect(await pyrcodeInput({"typed":"PYR-LT"} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"PYR-LT","complete":false});
  });

  it("anything else is kept, and is not a code", async () => {
    expect(await pyrcodeInput({"typed":"laptop"} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"LAPTOP","complete":false});
  });

  it("nothing typed", async () => {
    expect(await pyrcodeInput({"typed":""} as unknown as Parameters<typeof pyrcodeInput>[0])).toEqual({"code":"","complete":false});
  });
});
