// ── Flow node: frontend/utils/pyrcode-input ──
// Generated by Flow Studio from flow/frontend/utils/pyrcode-input.yaml. Edit the contract there; only the marked regions below belong to the implementer.
// <flow:imports>
// </flow:imports>

export interface PyrcodeInputInput {
  typed: string;
}

export interface PyrcodeInputOutput {
  code: string;
  complete: boolean;
}

// <flow:helpers>
const PYRCODE_PATTERN = /^PYR-[A-Z]{1,4}\d+(-\d+)?$/;
// </flow:helpers>

/** What someone typed or scanned into a Pyrcode field, in the form the backend looks it up by, and whether it is a whole code yet. */
export function pyrcodeInput(input: PyrcodeInputInput): PyrcodeInputOutput {
  // <flow:body>
  const code = input.typed.trim().toUpperCase();
  return { code, complete: PYRCODE_PATTERN.test(code) };
  // </flow:body>
}
